package consts;

public class AttributeConst {
    public static final short TAN_CONG = 0; // isPercent: 0; Tấn công
    public static final short THU_VAT = 1; // isPercent: 0; Thủ vật
    public static final short NE_TRANH = 2; // isPercent: 2; Né tránh
    public static final short CHINH_XAC = 3; // isPercent: 2; Chính xác
    public static final short CHI_MANG = 4; // isPercent: 2; Chí mạng
    public static final short SUC_KHOE = 5; // isPercent: 0; Sức khỏe
    public static final short THU_MA = 6; // isPercent: 0; Thủ ma
    public static final short CHI_SO_7 = 7; // isPercent: 0; chỉ số 7
    public static final short CHI_SO_8 = 8; // isPercent: 0; chỉ số 8
    public static final short CHI_SO_9 = 9; // isPercent: 0; chỉ số 9
    public static final short TANG_SUC_MANH = 10; // isPercent: 0; Tăng sức mạnh
    public static final short TANG_NHANH_NHEN = 11; // isPercent: 0; Tăng nhanh nhẹn
    public static final short TANG_TINH_THAN = 12; // isPercent: 0; Tăng tinh thần
    public static final short TANG_SUC_KHOE = 13; // isPercent: 0; Tăng sức khoẻ
    public static final short GAY_MU = 14; // isPercent: 1; Gây mù
    public static final short DONG_BANG = 15; // isPercent: 1; Đóng băng
    public static final short TRUNG_DOC = 16; // isPercent: 1; Trúng độc
    public static final short GAY_CHOANG = 17; // isPercent: 1; Gây choáng
    public static final short HOA_THACH = 18; // isPercent: 1; Hoá thạch
    public static final short GIAM_TOC = 19; // isPercent: 1; Giảm tốc
    public static final short KHANG_GIAM_TOC = 20; // isPercent: 1; Kháng giảm tốc
    public static final short KHANG_TRUNG_DOC = 21; // isPercent: 1; Kháng trúng độc
    public static final short KHANG_GAY_MU = 22; // isPercent: 1; Kháng gây mù
    public static final short KHANG_DONG_BANG = 23; // isPercent: 1; Kháng đóng băng
    public static final short KHANG_GAY_CHOANG = 24; // isPercent: 1; Kháng gây choáng
    public static final short KHANG_HOA_THACH = 25; // isPercent: 1; Kháng hoá thạch
    public static final short TANG_X2_MOI_LAN_DANH = 26; // isPercent: 1; Tăng x2 mỗi lần đánh
    public static final short TANG_TY_LE_ROT_BAO_VAT = 27; // isPercent: 1; Tăng tỷ lệ rớt bảo vật
    public static final short GIAM_ST_VAT = 28; // isPercent: 1; Giảm st vật
    public static final short GIAM_ST_MA = 29; // isPercent: 1; Giảm st ma
    public static final short TANG_TAN_CONG = 30; // isPercent: 1; Tăng tấn công
    public static final short XUYEN_GIAP = 31; // isPercent: 1; Xuyên giáp
    public static final short PHAN_ST = 32; // isPercent: 1; Phản st
    public static final short TANG_HP = 33; // isPercent: 0; Tăng HP
    public static final short TANG_MP = 34; // isPercent: 0; Tăng MP
    public static final short CONG_SUC_MANH = 35; // isPercent: 0; Cộng sức mạnh
    public static final short CONG_KHEO_LEO = 36; // isPercent: 0; Cộng khéo léo
    public static final short CONG_TINH_THAN = 37; // isPercent: 0; Cộng tinh thần
    public static final short CONG_SUC_KHOE = 38; // isPercent: 0; Cộng sức khoẻ
    public static final short CONG_KY_NANG = 39; // isPercent: 0; Cộng kỹ năng
    public static final short TANG_CHI_MANG = 40; // isPercent: 0; Tăng chí mạng
    public static final short TANG_ST_CHI_MANG = 41; // isPercent: 0; Tăng st chí mạng
    public static final short CHUA_DUNG = 42; // isPercent: 0; chưa dùng
    public static final short KY_NANG_1_CONG_THEM = 43; // isPercent: 0; kỹ năng 1 cộng thêm
    public static final short KY_NANG_2_CONG_THEM = 44; // isPercent: 0; kỹ năng 2 cộng thêm
    public static final short KY_NANG_3_CONG_THEM = 45; // isPercent: 0; kỹ năng 3 cộng thêm
    public static final short KY_NANG_4_CONG_THEM = 46; // isPercent: 0; kỹ năng 4 cộng thêm
    public static final short KY_NANG_5_CONG_THEM = 47; // isPercent: 0; kỹ năng 5 cộng thêm
    public static final short KY_NANG_6_CONG_THEM = 48; // isPercent: 0; kỹ năng 6 cộng thêm
    public static final short KY_NANG_7_CONG_THEM = 49; // isPercent: 0; kỹ năng 7 cộng thêm
    public static final short KY_NANG_8_CONG_THEM = 50; // isPercent: 0; kỹ năng 8 cộng thêm
    public static final short KY_NANG_9_CONG_THEM = 51; // isPercent: 0; kỹ năng 9 cộng thêm
    public static final short KY_NANG_10_CONG_THEM = 52; // isPercent: 0; kỹ năng 10 cộng thêm
    public static final short KY_NANG_11_CONG_THEM = 53; // isPercent: 0; kỹ năng 11 cộng thêm
    public static final short KY_NANG_12_CONG_THEM = 54; // isPercent: 0; kỹ năng 12 cộng thêm
    public static final short KY_NANG_13_CONG_THEM = 55; // isPercent: 0; kỹ năng 13 cộng thêm
    public static final short KY_NANG_14_CONG_THEM = 56; // isPercent: 0; kỹ năng 14 cộng thêm
    public static final short KY_NANG_15_CONG_THEM = 57; // isPercent: 0; kỹ năng 15 cộng thêm
    public static final short TANG_CONG = 58; // isPercent: 1; Tăng công
    public static final short TANG_THU_MA = 59; // isPercent: 1; Tăng thủ ma
    public static final short TANG_THU_VAT = 60; // isPercent: 1; Tăng thủ vật
    public static final short BO_QUA_TC_MA = 61; // isPercent: 1; Bỏ qua tc ma
    public static final short BO_QUA_TC_VAT = 62; // isPercent: 1; Bỏ qua tc vật
    public static final short TANG_THU_MA_TRANG_BI = 63; // isPercent: 1; Tăng thủ ma trang bị
    public static final short TANG_THU_VAT_TRANG_BI = 64; // isPercent: 1; Tăng thủ vật trang bị
    public static final short BAO_KICH = 65; // isPercent: 2; Bạo kích
    public static final short SET_LAN = 66; // isPercent: 2; Sét lan
    public static final short DOC_LAN = 67; // isPercent: 2; Độc lan
    public static final short BANG_LAN = 68; // isPercent: 2; Băng lan
    public static final short TANG_SET_LAN = 69; // isPercent: 2; Tăng sét lan
    public static final short TANG_DOC_LAN = 70; // isPercent: 2; Tăng độc lan
    public static final short TANG_BANG_LAN = 71; // isPercent: 2; Tăng băng lan
    public static final short TANG_ST_BANG_LAN = 72; // isPercent: 1; Tăng st băng lan
    public static final short TANG_ST_SET_LAN = 73; // isPercent: 1; Tăng st sét lan
    public static final short TANG_ST_DOC_LAN = 74; // isPercent: 1; Tăng st độc lan
    public static final short HOA_NGUOI_TUYET = 75; // isPercent: 2; Hoá người tuyết
    public static final short KHANG_BAO_KICH = 76; // isPercent: 0; Kháng bạo kích
    public static final short HUT_MAU = 77; // isPercent: 0; Hút máu
    public static final short HOI_HP = 78; // isPercent: 0; Hồi HP
    public static final short HOI_MP = 79; // isPercent: 0; Hồi MP
    public static final short TAN_PHE = 80; // isPercent: 2; Tàn phế
    public static final short HAP_THU_SAT_THUONG = 81; // isPercent: 0; Hấp thu sát thương
    public static final short CAM_LANG = 82; // isPercent: 2; Câm lặng
    public static final short TANG_TY_LE_ROT_VAT_PHAM = 83; // isPercent: 2; Tăng tỷ lệ rớt vật phẩm
    public static final short TANG_TY_LE_ROT_XU = 84; // isPercent: 2; Tăng tỷ lệ rớt xu
    public static final short KHANG_BANG_LAN = 85; // isPercent: 2; Kháng băng lan
    public static final short KHANG_SET_LAN = 86; // isPercent: 2; Kháng sét lan
    public static final short KHANG_DOC_LAN = 87; // isPercent: 2; Kháng độc lan
    public static final short TANG_THU_TRANG_BI = 88; // isPercent: 2; Tăng thủ trang bị
    public static final short LUA_LAN = 89; // isPercent: 2; Lửa lan
    public static final short TANG_LUA_LAN = 90; // isPercent: 2; Tăng lửa lan
    public static final short TANG_ST_LUA_LAN = 91; // isPercent: 1; Tăng st lửa lan
    public static final short KHANG_LUA_LAN = 92; // isPercent: 2; Kháng lửa lan
    public static final short ST_HAC_AM = 93; // isPercent: 0; St hắc ám
    public static final short ST_ANH_SANG = 94; // isPercent: 0; St ánh sáng
    public static final short XH_HAC_AM = 95; // isPercent: 2; Xh hắc ám
    public static final short XH_ANH_SANG = 96; // isPercent: 2; Xh ánh sáng
    public static final short GAY_HOANG_SO = 97; // isPercent: 0; Gây hoảng sợ:
    public static final short XH_HOANG_SO = 98; // isPercent: 1; Xh hoảng sợ
    public static final short ST_THEO_CHU = 99; // isPercent: 1; St theo chủ
    public static final short SUC_KHOE_2 = 100; // isPercent: 0; Sức khoẻ
    public static final short ST_MAX_HP = 101; // isPercent: 1; St max Hp
    public static final short RU_NGU = 102; // isPercent: 2; Ru ngủ
    public static final short CHOANG = 103; // isPercent: 2; Choáng
    public static final short BONG = 104; // isPercent: 2; Bỏng
    public static final short TRUNG_DOC_2 = 105; // isPercent: 2; Trúng độc
    public static final short SUY_YEU = 106; // isPercent: 2; Suy yếu
    public static final short CHUYEN_ST_QUA_MP = 107; // isPercent: 0; Chuyển st qua mp
    public static final short GIA_TANG_TC = 108; // isPercent: 0; Gia tăng tc
    public static final short HUT_HP = 109; // isPercent: 0; Hút hp
    public static final short SAT_THUONG_DOC = 110; // isPercent: 0; Sát thương độc
    public static final short TANG_EXP = 111; // isPercent: 1; Tăng exp
    public static final short TAC_DONG_SUY_YEU = 112; // isPercent: 1; Tác động suy yếu
    public static final short TL_HUT_HP = 113; // isPercent: 2; Tl hút hp
    public static final short NHAN_THEM_ST_KHI_BONG = 114; // isPercent: 1; Nhân thêm st khi bỏng
    public static final short SAT_THUONG_CHUAN = 115; // isPercent: 2; Sát thương chuẩn
    public static final short CHI_SO_VU_KHI_TANG = 116; // isPercent: 2; Chỉ số vũ khí tăng
    public static final short TY_LE_GAY_SAT_THUONG_CHUAN = 117; // isPercent: 2; Tỷ lệ gây sát thương chuẩn
    public static final short GIAM_SAT_THUONG_CUOI = 118; // isPercent: 2; Giảm sát thương cuối
    public static final short NGUYET_ANH_GAY_ST_10_15_TL_XUAT_HIEN = 119; // isPercent: 2; Nguyệt ảnh gây st(10%-15%) tl
                                                                          // xuất hiện
    public static final short KHANG_HOA = 120; // isPercent: 2; Kháng hoả
    public static final short KHANG_THUY = 121; // isPercent: 2; Kháng thuỷ
    public static final short KHANG_MOC = 122; // isPercent: 2; Kháng mộc
    public static final short KHANG_KIM = 123; // isPercent: 2; Kháng kim
    public static final short KHANG_THO = 124; // isPercent: 2; Kháng thổ
    public static final short GIA_LUONG = 125; // isPercent: 0; Giá lượng
    public static final short SO_LUONG = 126; // isPercent: 0; Số lượng
}
